### ISSUE TITLE
Linux下获取内存信息异常

### ISSUE THREAD

**Issue by huangchangxu** [whuanle/CZGL.SystemInfo#20]
![image](https://user-images.githubusercontent.com/32791392/209429177-3f9be901-834f-4bb6-95bf-9f11acec7dfc.png)

**Comment by whuanle** [comment]
用的是 net7 还是之前的版本

**Comment by whuanle** [comment]
你的 Linux 版本是啥，内核版本是啥

**Comment by whuanle** [comment]
你的 Linux 版本是啥，内核版本是啥

**Comment by huangchangxu** [comment]
net6  引用的CZGL.SystemInfo最新版本。
系统信息如截图：
![image](https://user-images.githubusercontent.com/32791392/209893513-6efbcb35-ee94-406e-9929-3645c150db23.png)

**Comment by LeZi9916** [comment]
> net6 引用的CZGL.SystemInfo最新版本。 系统信息如截图： ![image](https://user-images.githubusercontent.com/32791392/209893513-6efbcb35-ee94-406e-9929-3645c150db23.png)

这个问题好像在net6才有，net7并没有这个问题

**Comment by cfoan** [comment]
今天发现的linux内存占用率有问题，用的net7，CZGL.SystemInfo版本2.0.0.0。
获取的内存数据如下：
```
"TotalPhysicalMemory":959_877_120
"AvailablePhysicalMemory":83_779_584
"UsedPhysicalMemory":876_097_536
"UsedPercentage":0
```

UsedPercentage应该是91多，后查看代码大概是这里不对
CZGL.SystemInfo.LinuxMemory.GetMemory里面
![image](https://user-images.githubusercontent.com/12695081/219311193-00f9cf4d-e5ab-4d13-b845-1457c112f2ce.png)

**Comment by whuanle** [comment]
@cfoan 
除了百分比外，其它数值应该没问题吧

**Comment by whuanle** [comment]
![image](https://user-images.githubusercontent.com/2189761/220479770-12605e56-d6c7-462e-9443-9de71c48591c.png)

**Comment by whuanle** [comment]
@cfoan @huangchangxu @XiaoSong0919 
问题修复了。
另外关于 6.0，7.0 的问题，做了处理，7.0 支持 Native AOT，6.0 使用旧方法。

**Comment by Hyalei** [comment]
> @cfoan @huangchangxu @XiaoSong0919 问题修复了。 另外关于 6.0，7.0 的问题，做了处理，7.0 支持 Native AOT，6.0 使用旧方法。
我今天使用Linux测试的内存信息的代码，发现报错仍然存在，以下是我的代码片段和系统信息，我是用的是dotnet6.0

![代码片段](https://user-images.githubusercontent.com/91814111/227448851-f11998bb-9a90-48ad-b265-4091d95f6389.png)

![NuGet包版本](https://user-images.githubusercontent.com/91814111/227448520-33a682f4-9747-4d79-9170-4201cfde8aa0.png)

![获取Linux内存异常](https://user-images.githubusercontent.com/91814111/227448541-9cd688ff-2bf0-4cb2-aeb0-ed13012de1aa.png)

![linux内核信息](https://user-images.githubusercontent.com/91814111/227448556-3e1606e5-d8fd-4d98-80df-20ede40798dd.png)

**Comment by whuanle** [comment]
方便加微信么



---Original---
From: ***@***.***&gt;
Sent at: 2023年3月24日(Fri) PM3:04
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [whuanle/CZGL.SystemInfo] Linux下获取内存信息异常 (Issue #20)




  
@cfoan @huangchangxu @XiaoSong0919 问题修复了。 另外关于 6.0，7.0 的问题，做了处理，7.0 支持 Native AOT，6.0 使用旧方法。
 我今天使用Linux测试的内存信息的代码，发现报错仍然存在，以下是我的代码片段和系统信息

**Comment by Hyalei** [comment]
19903888974



发自我的iPad


------------------ 原始邮件 ------------------
发件人: whuanle ***@***.***&gt;
发送时间: 2023年3月24日 19:21
收件人: whuanle/CZGL.SystemInfo ***@***.***&gt;
抄送: Hyalei ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[whuanle/CZGL.SystemInfo] Linux下获取内存信息异常 (Issue #20)





 方便加微信么 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Sent at: 2023年3月24日(Fri) PM3:04 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 Subject: Re: [whuanle/CZGL.SystemInfo] Linux下获取内存信息异常 (Issue #20) 
 
 
 
 
    
 @cfoan @huangchangxu @XiaoSong0919 问题修复了。 另外关于 6.0，7.0 的问题，做了处理，7.0 支持 Native AOT，6.0 使用旧方法。 
  我今天使用Linux测试的内存信息的代码，发现报错仍然存在，以下是我的代码片段和系统信息
