### ISSUE TITLE
最新版本获取linux已用内存不准

### ISSUE THREAD

**Issue by alinayaa** [whuanle/CZGL.SystemInfo#22]
- docker运行
- debian.11-x64下实际使用2.9G，程序获取使用6.21G
- debian.11-arm64下实际使用0.5G，程序获取使用1.49G
- windows 11准确
-看来linux docker内获取的多了2倍左右。

**Comment by whuanle** [comment]
Linux 获取的内存，有些不一样，把缓存也计进去的。
你在 linux 里，使用 free -lh 命令看看。





---Original---
From: ***@***.***&gt;
Sent at: 2023年4月3日(Mon) PM3:27
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [whuanle/CZGL.SystemInfo] 最新版本获取linux已用内存不准 (Issue #22)




  
docker运行
 
debian.11-x64下实际使用2.9G，程序获取使用6.21G
 
debian.11-arm64下实际使用0.5G，程序获取使用1.49G
 
windows 11准确
 -看来linux docker内获取的多了2倍左右。
