### ISSUE TITLE
如何在容器中获取在应用程序在本容器使用的内存

### ISSUE THREAD

**Issue by jovi-Li** [whuanle/CZGL.SystemInfo#24]
如题

**Comment by whuanle** [comment]
之前是有这种 API 的，后面发现不实用，删除了

**Comment by whuanle** [comment]
看看旧版本 https://github.com/whuanle/CZGL.SystemInfo/blob/0.1/CZGL.SystemInfo/Info/MachineRunInfo.cs

**Comment by whuanle** [comment]
` Process[] p = Process.GetProcesses(); ` 可以拿到所有进程的信息，[Process.GetCurrentProcess](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.getcurrentprocess?view=net-7.0) 可以拿到当前进程的信息

**Comment by jovi-Li** [comment]
后来使用docker api去拿了 谢谢
